# Generated by Django 2.0.8 on 2018-11-16 19:21

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile("^[a-zA-Z '\\-]+$"), 'Enter a valid first_name', 'invalid')])),
                ('last_name', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(re.compile("^[a-zA-Z '\\-]+$"), 'Enter a valid last_name', 'invalid')])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Put their primary phone number here. Put additional phone numbers in the Notes field.', max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, default='San Francisco', max_length=50, validators=[django.core.validators.RegexValidator(re.compile("^[a-zA-Z '\\-]+$"), 'Enter a valid city', 'invalid')])),
                ('zip', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(re.compile('^\\d{5}$'), 'Enter a valid 5 digit zip code', 'invalid')], verbose_name='Zip Code')),
                ('notes', models.TextField(blank=True, verbose_name='Notes and Comments')),
            ],
        ),
    ]
