# Generated by Django 2.0.8 on 2018-11-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
